<p style="font-family: 'Arial';font-weight:bold; color: DeepSkyBLue;font-size:32px;text-shadow: 5px 5px 10px rgba(0,0,0,0.15);">Assignment 1 - Data Science <br> Student ID: 1221140 <br> Name: Ibrahim AbuHashhash</p>
<hr>

<p style="font-family: 'Arial'; font-style: italic;color: black;font-size:14px;">Importing necessary libraries. Pandas and Numpy.</p>

In [1]:
import pandas as pd 
import numpy as np

<hr>
<p style="font-family: 'Arial';font-style: italic;font-weight:bold; color:#36AF51;text-shadow: 5px 5px 10px rgba(0,0,0,0.15);font-size:19px;">- Question 1:  Identify the most expensive vegetables and fruits commodity <span style="color: red;">during this period.</span></p>

In [3]:
df = pd.read_csv(r"C:\Users\ibrah\Downloads\assignment_1-python.csv")

max_price = df['price'].max()

most_expensive = df[(df['price'] == max_price) & (df['date'].apply(lambda x: x.split('-')[0] == '2022'))]

result_df = most_expensive[['commodity', 'price', 'date']]

result_df

                        commodity  price        date
118  Rice (small grain, imported)  155.0  2022-05-15
147  Rice (small grain, imported)  155.0  2022-06-15
205  Rice (small grain, imported)  155.0  2022-08-15
234  Rice (small grain, imported)  155.0  2022-09-15
263  Rice (small grain, imported)  155.0  2022-10-15
294  Rice (small grain, imported)  155.0  2022-11-15

<p style="font-family: 'Arial'; font-style: italic;color: black;font-size:14px;"> The code reads a CSV file using the <strong>read_csv()</strong>  method, then finds the price of the most expensive commodity using the <strong>max()</strong> method. It then identifies the commodities that have the maximum price and prints the names of these most expensive commodities along with their price in ILS and date. Since each commodity has a different date, they won't be considered duplicates; therefore, all commodities with different dates will be printed <span style="color: red;">,The use of <strong>lambda</strong> function ensures that all the commodities are specific to this period only as <strong>mentioned in the question</strong></span>.
</p>
<hr>

<p style="font-family: 'Arial';font-style: italic;font-weight:bold; color:#36AF51;text-shadow: 5px 5px 10px rgba(0,0,0,0.15);font-size:19px;">- Question 2:  Add a new column named currency_rate that captures the exchange rate between the local currency and the US dollar (USD).
</p>

In [4]:
df['currency_rate'] = df.apply(lambda row: row['price'] / row['usdprice'] if row['usdprice'] != 0 else None, axis=1)
df[['commodity', 'price', 'usdprice', 'currency_rate']]

                           commodity   price  usdprice  currency_rate
0                              Bread    2.50    0.7934       3.150996
1             Potatoes (medium size)    1.94    0.6157       3.150885
2       Rice (small grain, imported)  152.31   48.3351       3.151126
3    Wheat flour (locally processed)   90.00   28.5612       3.151128
4                               Eggs   11.72    3.7193       3.151131
..                               ...     ...       ...            ...
349                      Cauliflower    2.95    0.8626       3.419893
350           Cucumbers (greenhouse)    1.83    0.5351       3.419922
351                Eggplants (large)    1.95    0.5702       3.419853
352              Onions (dry, local)    2.06    0.6023       3.420222
353            Tomatoes (greenhouse)    2.92    0.8538       3.420005

[354 rows x 4 columns]

<p style="font-family: 'Arial'; font-style: italic;color: black;font-size:14px;"> 
The code uses a <Strong>lambda</Strong> function to calculate the rate of ILS/USD. It then applies this function to each row of the DataFrame df, creating a new column named Currency_rate that contains the calculated rates for each item. it then displays specific columns, including the new <strong>Currency_rate</strong> column.</p>
<hr>

<p style="font-family: 'Arial';font-style: italic;font-weight:bold; color:#36AF51;text-shadow: 5px 5px 10px rgba(0,0,0,0.15);font-size:19px;">- Question 3: Create a new column called unified_price that represents the price in USD per kilogram for commodities measured by weight and the price per liter for commodities measured by volume.</p>

In [5]:
def unified_price(row):
    unit_info = row['unit'].split()

    if len(unit_info) < 2 and unit_info[0] in ['KG', 'L']:
        return row['usdprice'] / 1
    elif len(unit_info) == 2 and unit_info[-1] in ['KG', 'L']:
        amount = float(unit_info[0])
        return row['usdprice'] / amount
    else:
        return None

df['unified_price'] = df.apply(unified_price, axis=1)

df[['unit', 'usdprice', 'unified_price']]

      unit  usdprice  unified_price
0       KG    0.7934       0.793400
1       KG    0.6157       0.615700
2    25 KG   48.3351       1.933404
3    50 KG   28.5612       0.571224
4     2 KG    3.7193       1.859650
..     ...       ...            ...
349     KG    0.8626       0.862600
350     KG    0.5351       0.535100
351     KG    0.5702       0.570200
352     KG    0.6023       0.602300
353     KG    0.8538       0.853800

[354 rows x 3 columns]

<p style="font-family: 'Arial'; font-style: italic;color: black;font-size:14px;"> 
The code provides the <strong>unified_price</strong> function that determines the common price for a given commodity measured in a certain unit. It divides the unit string and determines whether it has <strong>singular or divisional</strong> units: if it is just a single unit without a number (for example “KG” or “L”), it returns the usdprice; while in the case of with number (for example with “5 KG” it takes the usdprice number and divides it with that number). It does return None, if the format is not understood, while the function is used on the DataFrame to return a new column <strong>‘unified_price’</strong> with the calculated values.
</p>
<hr>

<p style="font-family: 'Arial';font-style: italic;font-weight:bold; color:#36AF51;text-shadow: 5px 5px 10px rgba(0,0,0,0.15);font-size:19px;">- Question 4: Using the unified_price, find the maximum price reached during this period and for which commodity for both:
commodities measured by weight
commodities measured by volume.</p>

In [6]:
weight = df[df['unit'].apply(lambda x: x.split()[-1] == 'KG')]

max_weight = weight['unified_price'].max()

max_weight_commodity = weight.loc[weight['unified_price'] == max_weight, 'unit'].values

volume = df[df['unit'].apply(lambda x: x.split()[-1] == 'L')]

max_volume = volume['unified_price'].max()

max_volume_commodity = volume.loc[volume['unified_price'] == max_volume, 'unit'].values

print(f"Max price for weight commodities: {max_weight} USD for {max_weight_commodity}")
print(f"Max price for volume commodities: {max_volume} USD for {max_volume_commodity}")

Max price for weight commodities: 17.3144 USD for ['KG']
Max price for volume commodities: 3.192 USD for ['3 L']

<p style="font-family: 'Arial'; font-style: italic;color: black;font-size:14px;"> 
The code selects from the Data Frame only those commodities which are examined in weight (KG) and volume (L) and assigns it to variables <strong>weight</strong> and  <strong>volume</strong>. It uses a <strong>max()</strong> function to determine the maximum available value of the unified_price for both classes of commodity and fetches the required commodity names corresponding to each price. The output for weight and volume category of the maximum price is also displayed in a single string where values of maximum prices are shown along with names of the products.
</p>
<hr>